# Generated by Django 5.2.1 on 2025-06-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название полезного ископаемого')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('extraction_url', models.URLField(verbose_name='Ссылка на добычу (Datawrapper)')),
                ('reserves_url', models.URLField(verbose_name='Ссылка на запасы (Datawrapper)')),
            ],
            options={
                'verbose_name': 'Полезное ископаемое',
                'verbose_name_plural': 'Полезные ископаемые',
            },
        ),
    ]
